# Generated by Django 2.1.3 on 2018-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('msid', models.CharField(max_length=512, null=True)),
                ('access_token', models.CharField(max_length=1024, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
