# Generated by Django 2.1.3 on 2018-12-29 06:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('msid', models.CharField(max_length=512, null=True)),
                ('token', jsonfield.fields.JSONField()),
                ('access_token', models.CharField(max_length=2048, null=True)),
                ('access_token_exp', models.PositiveIntegerField(default=3599)),
                ('refresh_token', models.CharField(max_length=2048, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
