# Generated by Django 2.1.3 on 2019-01-06 06:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181229_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('body', models.CharField(max_length=1000)),
                ('redirect_url', models.URLField()),
                ('reply_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sent', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='access_token_exp',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
