# Generated by Django 2.1.3 on 2019-01-06 06:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190106_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmail',
            name='reply_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
