# Generated by Django 2.1.3 on 2019-01-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190106_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('login_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MassInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='mass_invite_files')),
            ],
        ),
    ]
