# Generated by Django 2.1.3 on 2018-12-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientUser',
        ),
    ]
