# Generated by Django 2.1.3 on 2018-12-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20181226_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='msid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
