# Generated by Django 2.1.3 on 2018-12-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_clientuser_msid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='msid',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
