# Generated by Django 2.1.3 on 2018-12-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20181227_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='access_token',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
